config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'surveys#index'

  resources :surveys do
    resources :answers, only: %i[create show]
    post 'answer', to: 'surveys#answer'
    get 'fill_out', to: 'surveys#fill_out'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :answer, :question_id, presence: true
  validates :answer, uniqueness: { scope: :question_id }
  validates :count, numericality: { greater_than: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question, :question_types_id, presence: true
  validates :survey_id, uniqueness: { scope: :question, message: 'already exists' }
  validate :validate_options_for_closed_answer
  serialize :options, Array

  attribute :answer, :string
  belongs_to :survey, required: true
  belongs_to :question_type, foreign_key: :question_types_id, primary_key: 'name', required: true

  has_many :answers, dependent: :destroy

  private

  def validate_options_for_closed_answer
    if question_types_id == 'closed_answer'
      if !options.is_a?(Array) || options.length != 4 || options.any? { |option| !option.is_a?(String) || option.blank? }
        errors.add(:options, 'Options must be an exactly 4 non-empty fields for closed answer questions.')
      end
    elsif options != []
      errors.add(:options, 'Options should not be present for non-closed answer questions.')
    end
  end
end

app/models/question_type.rb
class QuestionType < ApplicationRecord
  validates :name, :display_name, presence: true
  validates :name, uniqueness: true
end

app/models/survey.rb
class Survey < ApplicationRecord
  validates :title, :questions, presence: true
  validates :questions, length: { minimum: 1, message: 'must have at least one question' }

  has_many :questions, dependent: :destroy
  belongs_to :user

  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :surveys
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @survey = Survey.find(params[:survey_id])
    answers = answers_params[:questions_attributes].values.map do |answer|
      Answer.find_or_initialize_by(question_id: answer[:question_id], answer: answer[:answer])
            .increment(:count)
    end
    Answer.transaction do
      answers.each(&:save!)
    end
    if @survey.questions.count == answers_params[:questions_attributes].values.count
      redirect_to root_path, notice: 'Survey completed!'
    end

  rescue ActiveRecord::RecordInvalid => e
    flash[:alert] = e.message
    render 'surveys/fill_out', survey: @survey, status: :unprocessable_entity
  end

  def show
    @survey = Survey.find(params[:id])
  end

  private

  def answers_params
    params.require(:survey).permit(questions_attributes: %i[question_id answer id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[show edit update destroy fill_out]
  before_action :set_question_types, only: %i[new edit create update]
  before_action :authenticate_user!, except: %i[index fill_out]

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1/fill_out
  def fill_out; end

  # GET /surveys/1 or /surveys/1.json
  def show
    @responses = @survey.questions.map(&:answers).flatten.map(&:count).sum / @survey.questions.count
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit; end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_url(@survey), notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update!(survey_params)
        format.html { redirect_to survey_url(@survey), notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_survey
    @survey = Survey.find(params[:id] || params[:survey_id])
  end

  def set_question_types
    @question_types = QuestionType.pluck(:display_name, :name)
  end

  # Only allow a list of trusted parameters through.
  def survey_params
    params.require(:survey).permit(:title, :user_id, :id,
                                   questions_attributes:
                                     [:id, :question, :question_types_id, :_destroy, { options: [] }])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>SurveyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-soft-white h-full">
    <header class="bg-gray-800 text-white">
      <div class="container mx-auto px-5">
        <nav class="grid grid-cols-2 items-center justify-between py-5 h-20">
          <a href="/" class="text-2xl font-bold col-span-1 hover:text-gray-300">SurveyApp</a>

          <div class="col-span-1 text-right">
            <% if user_signed_in? %>
              <%= current_user.email %>,
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "text-l font-bold hover:text-gray-300" %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "text-l font-bold hover:text-gray-300" %>
            |
            <%= link_to "Sign up", new_user_registration_path, class: "text-l font-bold hover:text-gray-300" %>
            <% end %>
          </div>
        </nav>
      </div>
    </header>
    <%= render "shared/flash" %>
    <main class="container mx-auto px-5 h-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/questions/_closed.html.erb
<div class="col-span-1">
  <%= f.label :options, "Option" %>
  <%= f.text_field :options, class: "w-full", multiple: true, value: option %>
</div>

app/views/questions/_form.html.erb
<div class="nested-fields gap-2 border-2 border-gray-600 p-4 mt-1 col-span-full">
  <div class="flex flex-wrap gap-2 justify-center justify-items-center">
    <div class="">
      <%= f.label :question_types_id, "Type", class: "block" %>
      <%= f.select :question_types_id,
                   options_for_select(@question_types, f.object.question_types_id || "open_answer"),
                   {},
                   class: "mt-auto h-10", onchange: "loadQuestionBasedOnType($(this))" %>
    </div>

    <div class="ml-4 w-3/4">
      <%= f.label :question, "Question", class: "block" %>
      <%= f.text_field :question, class: "w-full h-10", required: true %>
    </div>
    <%= link_to_remove_association button_tag("Delete", class: "text-white bg-red-600 hover:bg-red-400 rounded-lg p-2 w-32 h-10"), f, class: "mt-auto" %>
    <div id="closed_answers" class="grid-cols-full flex gap-4" style="<%= if f.object.question_types_id != "closed_answer"
                                                                            "display: none"
                                                                          end %>">
      <% (0..3).each do |index| %>
        <%= render "questions/closed",
                   f: f,
                   option: f.object.options[index],
                   required: f.object.question_types_id == "closed_answer" %>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/_question.html.erb
<div class="my-4">
  <h2 class="text-xl font-bold"><%= question.question_type.display_name %> - <%= question.question %></h2>
  <ul>
    <% if question.answers == [] %>
      <li>No responses yet</li>
    <% else %>
      <% question.answers.each do |answer|
        response = "response".pluralize(answer.count)
        answers_count = question.answers.map(&:count).sum
        answer_f = answer.count.to_f / answers_count
        answer_percentage = answer_f.round(2) * 100%>
        <li class="grid grid-cols-2 mb-2">
          <div class="col-span-1 w-72">
            <%= "#{answer.answer} - #{answer.count} #{response}" %>
          </div>
          <div class="flex col-span-1">
            <div class="w-16">
              <%= "#{answer_percentage.round(2)} %" %>
            </div>
            <div class="w-72 h-6 bg-gray-200 rounded-full">
              <div class="h-6 bg-blue-600 rounded-full" style="width: <%= answer_percentage.to_i %>%"></div>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/shared/_flash.html.erb
<% if notice %>
  <div id="notice" 
    class="flex items-center p-4 mb-4 text-green-800 rounded-lg bg-green-50"
    role="alert">
    <span class="sr-only">Notice</span>
    <div class="ml-3 text-sm font-medium">
      <%= notice %>
    </div>
  </div>
<% end %>

<% if alert %>
  <div id="alert"
    class="flex items-center p-4 mb-4 text-red-800 rounded-lg bg-red-50"
    role="alert">
    <span class="sr-only">Alert</span>
    <div class="ml-3 text-sm font-medium">
      <%= alert %>
    </div>
  </div>
<% end %>

app/views/shared/_model_errors_flash.html.erb
<% if model.errors.any? %>
  <div class="red col-span-full">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this survey from being saved:</h2>

    <ul>
      <% model.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/surveys/_form.html.erb
<%= form_for @survey do |f| %>
  <div class="grid grid-cols-4 mt-4">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :id, value: @survey.id %>
    <%= render "shared/model_errors_flash", model: survey %>

    <div class="col-span-1">
      <%= f.label :title, "Survey name", class: "block" %>
      <%= f.text_field :title, required: true %>
    </div>

    <div class="col-span-full mt-4"> Questions</div>
    <div id="questions" class="col-span-full mt-1">
      <%= f.fields_for :questions do |question_form|
        render 'questions/form', f: question_form
      end %>
    </div>
    <div class="col-span-full mt-4 text-right">
      <%= link_to_add_association button_tag("Add Question",
                                             class: "text-white bg-blue-600 hover:bg-blue-400 rounded-lg p-2 w-32 h-10"),
                                  f, :questions, partial: 'questions/form' %>
      <div class="mt-4">
        <%= link_to surveys_path do
          button_tag "Back to surveys",
                     class: "text-white bg-red-600 hover:bg-red-400 rounded-lg p-2 h-10"
        end %>

        <%= button_tag "Submit",
                       class: "text-white bg-green-600 hover:bg-green-400 rounded-lg p-2 w-34 h-10 pointer-events-auto" %>
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript">
    function loadQuestionBasedOnType(el) {
        console.log(el)
        let type = el.val();
        console.log(type);
        let questionAnswers = el.parent().parent().children("#closed_answers")
        console.log(questionAnswers)

        switch (type) {
            case "true_false":
            case "open_answer":
                questionAnswers.hide();
                break;
            case "closed_answer":
                questionAnswers.show();
                break;
            default:
                throw "Invalid question type";
        }
    }

</script>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>">
  <tr>
  <td>
    <strong>Title:</strong>
    <%= survey.title %>
  </td>

  <td>
    <strong>Author:</strong>
    <%= survey.author %>
  </td>

  </tr>

</div>

app/views/surveys/edit.html.erb
<h1 class="text-center text-3xl font-bold my-4">Edit survey</h1>

<%= render "form", survey: @survey %>

app/views/surveys/fill_out.html.erb
<h1 class="text-center text-3xl font-bold my-4"><%= @survey.title %></h1>
<%= form_for @survey, method: "post", url: survey_answers_path(@survey), html: { class: "grid grid-cols-5", id: "answer-form" } do |f| %>
  <%= f.fields_for :questions do |ff| %>
    <%= ff.hidden_field :question_id, value: ff.object.id %>
    <div class="border-gray-800 border-b border-collapse col-span-3 col-start-2 grid mb-1">
      <h3 class="text-xl font-bold mb-1"><%= ff.object.question %></h3>
      <% if ff.object.question_types_id == "open_answer" %>
        <%= ff.text_field :answer, class: "mb-1", required: true %>
      <% elsif ff.object.question_types_id == "closed_answer" then %>
        <div class="flex justify-around my-1">
          <% ff.object.options.each do |option| %>
            <div>
              <%= ff.radio_button :answer, option, required: true %>
              <%= ff.label :answer, option %>
            </div>
          <% end %>
        </div>
      <% elsif ff.object.question_types_id == "true_false" then %>
        <div class="flex justify-center gap-32 my-1">
          <div>
            <%= ff.radio_button :answer, "true", required: true %>
            <%= ff.label :answer, "True" %>
          </div>
          <div>
            <%= ff.radio_button :answer, "false", required: true %>
            <%= ff.label :answer, "False" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

<div class="text-right mt-4">
  <%= button_tag "Submit", form: "answer-form", class: "text-white bg-green-600 hover:bg-green-400 rounded-lg p-2 text-sm my-2 col-start-5" %>
  <% if current_user == @survey.user %>
    <%= link_to "Edit",
                edit_survey_path(@survey),
                class: "text-white bg-yellow-600 hover:bg-yellow-400 rounded-lg p-2 text-sm my-2 col-start-5" %>
    <%= link_to "Destroy this survey",
                @survey,
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: "text-white bg-red-600 hover:bg-red-400 rounded-lg p-2 text-sm my-2 col-start-5" %>
  <% end %>

  <%= link_to "Back to surveys", surveys_path, class: "text-white bg-blue-600 hover:bg-blue-400 rounded-lg p-2 text-sm my-2 col-start-5" %>
</div>

app/views/surveys/index.html.erb
<h1 class="text-center text-3xl font-bold my-4">Surveys</h1>
<div class="grid grid-cols-5">

<table id="surveys" class="col-span-full table-auto min-w-full min-h-3/5 border-2 border-collapse border-gray-800 mt-4 ">
  <thead class="border-b">
    <tr>
      <th class="border">Title</th>
      <th class="border">Author</th>
      <th class="border">Created at</th>
    </tr>
    <% @surveys.each do |survey| %>
      <tr class="border-b">
        <td class="text-center border"><%= survey.title %></td>
        <td class="text-center border"><%= survey.user.email %></td>
        <td class="text-center border"><%= survey.created_at.to_formatted_s(:short)%></td>
        <td class="text-center border p-1 w-72">
          <% if survey.user != current_user %>
            <%= link_to "Fill out", survey_fill_out_path(survey) , class: "text-sm text-white bg-green-600 hover:bg-green-400 rounded-md p-1"%>
          <% else %>
            <%= link_to "Results", survey_path(survey), class: "text-sm text-white bg-blue-600 hover:bg-blue-400 rounded-md p-1" %>
            <%= link_to "Edit", edit_survey_path(survey), class: "text-sm text-white bg-yellow-600 hover:bg-yellow-400 rounded-md p-1"%>
            <%= link_to "Delete", survey, method: :delete, data: { confirm: "Are you sure?" }, class: "text-sm text-white bg-red-600 hover:bg-red-400 rounded-md p-1"%>
          <% end %>
        </td>
      </tr>
    <% end %>
</table>

<%= link_to "New survey", new_survey_path,
  class: "text-white bg-green-600 hover:bg-green-400 rounded-lg p-2 text-sm my-2 col-start-5 mx-auto mr-0" %>

</div>

app/views/surveys/new.html.erb
<h1 class="text-center text-3xl font-bold my-4">New Survey</h1>

<%= render "form", survey: @survey %>

app/views/surveys/show.html.erb
<h1 class="text-center text-3xl font-bold my-4">Results for <%= @survey.title %></h1>
<h2 class="text-center text-2xl font-bold my-4">Total Responses: <%= @responses %></h2>

<% @survey.questions.each do |question| %>
  <%= render "questions/question", question: question %>
<% end %>


<div class="flex flex-row-reverse">
  <%= link_to surveys_path do
    button_tag "Back to surveys",
               class: "text-white bg-red-600 hover:bg-red-400 rounded-lg p-2 h-10"
  end %>
</div>